name: My Simple Workflow

on:
  workflow_dispatch:  # This enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install curl
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      # Step 3: Install jq
      - name: Install jq
        run: |
          sudo apt-get install -y jq

      # Step 4: Fetch IP information from ipinfo.io
      - name: Fetch IP information
        run: |
          echo "Fetching IP information from ipinfo.io..."
          ip_info=$(curl -s https://ipinfo.io/json)  # Fetch IP info in JSON format
          echo "IP info fetched successfully."

      # Step 5: Display the raw IP info JSON
      - name: Display Raw IP Info
        run: |
          echo "Raw IP Info:"
          echo "$ip_info"  # Display the raw JSON response

      # Step 6: Parse and display specific details (IP, City, Region, Country)
      - name: Parse and Display IP Info
        run: |
          ip_address=$(echo $ip_info | jq -r '.ip')
          city=$(echo $ip_info | jq -r '.city')
          region=$(echo $ip_info | jq -r '.region')
          country=$(echo $ip_info | jq -r '.country')

          echo "IP Address: $ip_address"
          echo "City: $city"
          echo "Region: $region"
          echo "Country: $country"
